### ISSUE TITLE
mapper.xml没适配lombklombok

### ISSUE THREAD

**Issue by milixiang** [baomidou/MybatisX#2]
![image](https://user-images.githubusercontent.com/12092768/80667040-a2f4bc00-8ad0-11ea-84fc-c91e72deea5c.png)
图中红色的字段在实体类内都有的  但是用的lombok  没有getset方法  加上getset就显示正常了

**Comment by tianyu94** [comment]
我也是这个问题，希望能支持，感谢作者开发的插件。

**Comment by yangyang0507** [comment]
请自行安装 lombok 插件，并打开 IDEA 中的 Preferences | Build, Execution, Deployment | Compiler | Annotation Processors 功能
