### ISSUE TITLE
当namespace指定的类不存在时报错

### ISSUE THREAD

**Issue by totoro52** [baomidou/MybatisX#20]
正常的mybatis支持自定义namespace名称，无需指定某个java的类，希望能加一个开关，用来决定是否需要验证接口类是否存在。
![image](https://user-images.githubusercontent.com/25952444/111962721-a0a6b080-8b2d-11eb-8c73-383d008ef325.png)

**Comment by ls9527** [comment]
不错的意见， 可以加入开关，预计在1.5.x加入
