### ISSUE TITLE
association、collection的javaType和ofType字段映射的不正确问题

### ISSUE THREAD

**Issue by xiyou1223** [baomidou/MybatisX#22]
社区版IDEA，xml里association、collection的javaType和ofType字段映射的不正确，都是映射的外层的type的实体类的属性。

![1](https://user-images.githubusercontent.com/5792490/114667528-26370e00-9d32-11eb-941b-66506274a378.png)
![2](https://user-images.githubusercontent.com/5792490/114667535-27683b00-9d32-11eb-9970-266d8f3ca2e8.png)

**Comment by ls9527** [comment]
最新版本已修复
