### ISSUE TITLE
sql/resultMap/select with such name already exists

### ISSUE THREAD

**Issue by Wuyiz** [baomidou/MybatisX#27]
- 加了个字段，然后使用mybatis-generator重新生成并覆盖原有的mapper和xml后，xml中的id会提示名称已存在；
- 
- 尝试重启idea不行
- 清除idea缓存并重启也不行
- 禁用mybatisX插件后，不提示错误了，但是再重新打开插件后又会提示错误
- 
- 只有在删除原有的mapper和xml后，再使用generator生成新的文件才能消除错误提示

![微信截图_20210519123620](https://user-images.githubusercontent.com/42826957/118757406-a4da1a80-b89f-11eb-9263-4743cb549696.png)

![微信截图_20210519124011](https://user-images.githubusercontent.com/42826957/118757649-17e39100-b8a0-11eb-8733-605b530ad86e.png)

**Comment by Wuyiz** [comment]
mybatisX 版本：1.4.13
idea：ultimate 2020.3

**Comment by ls9527** [comment]
已修复

**Comment by Alanggggg** [comment]
怎么修复
