### ISSUE TITLE
建议增加sql嵌入的ONGL表达式的支持

### ISSUE THREAD

**Issue by meiMingle** [baomidou/MybatisX#31]
建议增加sql嵌入的ONGL表达式的支持(语法分析和跳转),如下图,其中RoadshowType是枚举类,![image](https://user-images.githubusercontent.com/39942874/121287602-6ff83b00-c914-11eb-8a8b-ce667371426b.png)
![image](https://user-images.githubusercontent.com/39942874/121287661-8ef6cd00-c914-11eb-805c-6f95f1a1c8a4.png)

**Comment by qingmo** [comment]
那你这个是想根据name来反解析为enum？

**Comment by qmdx** [comment]
请使用 typeHandler 处理
