### ISSUE TITLE
生成代码问题

### ISSUE THREAD

**Issue by lmiao2017** [baomidou/MybatisX#33]
mapper写了方法之后  generate mybatis sql 没反应

**Comment by ls9527** [comment]
generate mybatis sql 没反应， 那应该是报错了.  
 
 对于错误信息， 需要知道 以下信息:
1. jpa 拼写全称, 例如:  selectNameAndAgeById
2. resultMap 映射
3. 有关JPA字段的实体类信息

有了这三个信息之后, 就可以复现并且解决BUG了

**Comment by lmiao2017** [comment]
感谢回复，我之后已经成功生成了代码
