### ISSUE TITLE
功能请求：期望模板变量能提供更多数据库字段信息

### ISSUE THREAD

**Issue by junxy** [baomidou/MybatisX#36]
最近更新的 `custom-model-swagger` 模板很赞
期望模板变量`字段信息`能提供更多数据库字段信息
比如：
1. 字段是否为空，方便判断生成swagger时加上 `@NotNull`、`@NotEmpty` 注解 
2. 字段是否启用自增，方便自己写的domain也能像内置的那样支持设置 `@TableId` 的 type，ID生成方式

**Comment by ls9527** [comment]
预计 1.4.17 加入
