### ISSUE TITLE
可以从xml跳转到mapper,无法从mapper跳转到xml

### ISSUE THREAD

**Issue by txiot29** [baomidou/MybatisX#37]
idea 社区版 版本2021.1，mybatisx1.4.17 在线安装的
![image](https://user-images.githubusercontent.com/20141634/126625411-49516330-59d5-4846-9c14-9e0a17fe0a94.png)
![image](https://user-images.githubusercontent.com/20141634/126625556-83d59c65-bc4f-475e-902d-75d45fefd324.png)

**Comment by ls9527** [comment]
通常的原因是 xml的namespace 和接口的全路径不一致引起的

**Comment by txiot29** [comment]
> 通常的原因是 xml的namespace 和接口的全路径不一致引起的

一致的，不一致还不报错了

**Comment by soutong** [comment]
同样遇到此问题了

**Comment by ls9527** [comment]
测不出来，  是每个项目都是如此吗？
用2021.2的社区版本仍然能正常跳转

**Comment by ls9527** [comment]
目前确认和mybatisPlus插件冲突， 会导致这个现象
