### ISSUE TITLE
希望能增加自定义生成的ServiceImpl实现类名后缀的功能

### ISSUE THREAD

**Issue by escyezi** [baomidou/MybatisX#38]
现在生成的ServiceImpl实现类名称都是实体类+Service，如实体类名是Student，对应的查询实现类生成的是StudentService和StudentImpl,import进来后容易和业务层的service类相混淆
是否可以自定义“Service”这个后缀，最终生成类似StudentXXX格式的如StudentStorageService

**Comment by ls9527** [comment]
支持，根据文档改模板就可以了.  

文档地址:  
https://baomidou.com/guide/mybatisx-idea-plugin.html#%E7%94%9F%E6%88%90%E4%BB%A3%E7%A0%81%E7%9A%84%E6%A8%A1%E6%9D%BF%E9%85%8D%E7%BD%AE

**Comment by escyezi** [comment]
感谢，找到修改的地方在.meta.xml了
如果文档能对此做些说明就好了
