### ISSUE TITLE
数据库类型tinyint(1)的时候映射错误

### ISSUE THREAD

**Issue by mydiycode** [baomidou/MybatisX#39]
当数据库类型为tinyint(1)的时候映射成bool类型了，tinyint(2)的时候映射的是Byte类型的。为什么要将1位的时候映射为bool类型，这个是基于什么考虑的？其实很多时候一个字段标识可能不止2种状态，但是又不会超过2位数，这个时候数据库其实就没必要定义未tinyint(2)，往往会定义为tinyint(1)，此时映射成bool就错了。这个1位的时候可以映射为Byte，如果需要用bool，数据库可以定义成bit就好了。

**Comment by ls9527** [comment]
```JAVA
# 数据库类型转换为JDBC Type的规则
# com.baomidou.plugin.idea.mybatisx.util.DbToolsUtils#convertTypeNameToJdbcType
 else if (fixed.contains("TINYINT")) {
                return size == 1 ? Types.BOOLEAN : Types.TINYINT;
            } 
#  jdbcType和java类型的映射关系
        typeMap.put(Types.BIT, new JdbcTypeInformation("BIT", //$NON-NLS-1$
                new FullyQualifiedJavaType(Boolean.class.getName())));
				
				        typeMap.put(Types.TINYINT, new JdbcTypeInformation("TINYINT", //$NON-NLS-1$
                new FullyQualifiedJavaType(Byte.class.getName())));
```

写死的,  按照默认的规则来定制, 当然也可以把这个部分抽离出来。
抽离出来就需要定制几套推荐模板才行， 你能推荐一下根据类型和长度转换为java类型的规则吗？

**Comment by mydiycode** [comment]
我认为对于数据库中定义为TINYINT，转化到java类型就应该是Byte，不需要去管数据库中定义的长度问题。如果他希望对应java中的Boolean，那么数据库中就应该定义为bit类型，而不是TINYINT。
