### ISSUE TITLE
在使用多数据环境时，希望跳转显示databaseId

### ISSUE THREAD

**Issue by thtns** [baomidou/MybatisX#40]
由于项目使用了多数据库环境，mapper跳转到xml文件时，会有多个选项 如下：
![image](https://user-images.githubusercontent.com/11975717/127130830-32c8d66c-d8c3-43d4-9e19-ee483f9152ab.png)

希望能在跳转时加上databaseId加以区分

**Comment by ls9527** [comment]
预计 1.5.0 解决
