### ISSUE TITLE
多层association标签是类型检查错误

### ISSUE THREAD

**Issue by wangyu-2024** [baomidou/MybatisX#41]
在mybatis中使用多层association聚组时，插件无法正确识别当前层级的property属性

```
<resultMap id="query" type="a">
        <association property="a1" javaType="b">
            ……
            <association property="b1" javaType="c">
                ……
            </association>
        </association>
    </resultMap>
```

上述代码 插件会校验b1不属于a类型而不是b类型

**Comment by ls9527** [comment]
插件版本是多少？

**Comment by wangyu-2024** [comment]
> 插件版本是多少？

插件版本 1.4.17
idea
IntelliJ IDEA 2021.2 (Ultimate Edition)
内部版本号 #IU-212.4746.92，July 27, 2021 构建

**Comment by wangyu-2024** [comment]
> 插件版本是多少？

你好，这个问题有修复计划吗

**Comment by ls9527** [comment]
预计1.5.1 修复

**Comment by ls9527** [comment]
不确定是修复了还是怎么样了， 源码的测试用例里面， com.baomidou.mybatis3.mapper.ExampleMapper 这里的嵌套映射能正常显示不报错
