### ISSUE TITLE
插件安装好后，右键表不展示生成选项

### ISSUE THREAD

**Issue by huh0ngtao** [baomidou/MybatisX#44]
idea版本：
IntelliJ IDEA 2018.2.5 (Ultimate Edition)
Build #IU-182.4892.20, built on October 16, 2018

插件重复安装，每次都重启，仍然不行
![2021-09-06_150539](https://user-images.githubusercontent.com/17877745/132174644-d764a291-2ff0-49f8-8889-44b9939e3d46.png)
![2021-09-06_150518](https://user-images.githubusercontent.com/17877745/132174652-a8169abc-8634-4ed4-93ee-7e4eaf8f9ff5.png)

麻烦大佬，帮忙看下，是因为编辑器的版本问题吗？

**Comment by ls9527** [comment]
编辑器1.4.x 之前最低需要2019.2.
1.5.x开始编辑器最低需要2020.2
