### ISSUE TITLE
生成代码问题

### ISSUE THREAD

**Issue by kevin-onepiece** [baomidou/MybatisX#47]
生成实体类时，package name 多出一个"."，不知道为什么。
![image](https://user-images.githubusercontent.com/36980899/140452762-97014aec-df16-43d6-9fa1-373eeb9af5ce.png)
![image](https://user-images.githubusercontent.com/36980899/140452824-c47f1c1d-9392-4c95-9e13-a0fe494406da.png)

**Comment by firekirin67** [comment]
[issues_50](https://github.com/baomidou/MybatisX/issues/50)
看这里  填写下relative package即可解决

**Comment by ls9527** [comment]
嗯， 预计下个版本解决。 1.5.2.
看一下有没有人提PR，没有我再改

**Comment by kevin-onepiece** [comment]
谢谢大佬们
