### ISSUE TITLE
插件在 typeHandler 字段上无法处理嵌套类

### ISSUE THREAD

**Issue by bromine0x23** [baomidou/MybatisX#49]
插件在 typeHandler 字段上无法处理嵌套类；相对的插件在 type 字段上能处理嵌套类

![image](https://user-images.githubusercontent.com/5657337/143983867-ea206c9c-8945-4cad-b35d-049e352b0c77.png)

**Comment by ls9527** [comment]
描述很明确， 预计1.5.2 修复这个BUG
