### ISSUE TITLE
Mapper接口的icon变了

### ISSUE THREAD

**Issue by ice-fun** [baomidou/MybatisX#5]
![image](https://user-images.githubusercontent.com/54355118/91378765-d283bd00-e853-11ea-9e99-33eb4771d01a.png)
接口icon变成了小鸟，强迫症看着好难受

**Comment by Nayacco** [comment]
+1

**Comment by ls9527** [comment]
1.3.9 版本开始可以从系统设置里面修改图标。 默认还是小鸟，可以改回系统默认的。
因为小鸟图标可以判断Mapper是不是有对应的xml文件，基于这个原因修改的图标。
![maper_icon](https://user-images.githubusercontent.com/6361319/102002775-d53eeb00-3d3a-11eb-8108-89948845ce82.png)
