### ISSUE TITLE
生成实体类时问题

### ISSUE THREAD

**Issue by firekirin67** [baomidou/MybatisX#50]
生成实体类时如果没有填写relative package将导致实体类报名以“.”结尾，并且mapper.xml引用也将多出个"."
问题在于
com.baomidou.plugin.idea.mybatisx.generate.template.GenerateCode .generate(Project project,
                                GenerateConfig generateConfig,
                                Map<String, List<TemplateSettingDTO>> templateSettingMap,
                                DbTable dbTable,
                                String domainName,
                                String tableName) throws Exception 
方法第89行
javaModelGeneratorConfiguration.setTargetPackage(generateConfig.getBasePackage() + "." + generateConfig.getRelativePackage());

未做空字符串判断直接进行了拼接
当然 如果在界面上填写了relative package可以规避

**Comment by ls9527** [comment]
你都找到问题所在了， 不介意的话，可以提个PR
