### ISSUE TITLE
启用插件会导致IDEA自带的Safe Delete没法传递（Propagate）删除

### ISSUE THREAD

**Issue by cest-la-v** [baomidou/MybatisX#54]
详见我在这里给IDEA官方建的issue，里面有包含问题情况、示例代码。
[Propagate Safe Delete doesn't work](https://youtrack.jetbrains.com/issue/IDEA-285485)

我遇到问题的MyBatisX版本为1.5.2

**Comment by ls9527** [comment]
好的， 下个版本修复

**Comment by cest-la-v** [comment]
好的感谢！
