### ISSUE TITLE
1个bug 2个feature

### ISSUE THREAD

**Issue by wqbill** [baomidou/MybatisX#58]
# BUG
联合主键会生成多个@TableId注解，贵司的mybatis-plus其实根本不支持联合主键，建议联合主键生成注解改成@TableField
# FEATURE
1. 自定义额外类注解（虽然有lombok勾选项但是只会加上`@Data`我个人总得手动添加`@AllArgsConstructor` `@NoArgsConstructor` `@Builder` `@Accessors(chain = true)`)
2. 字段加上`` ` ``选项（数据库字段可能为保留字段）

**Comment by ls9527** [comment]
@TableId 是mybatis-plus框架的问题，需要在指定地方提问。
注解是lombok插件提供的， 与本插件无关
