### ISSUE TITLE
返回参数支持 alias

### ISSUE THREAD

**Issue by Nayacco** [baomidou/MybatisX#9]
![image](https://user-images.githubusercontent.com/22909744/101058324-faf42380-35c7-11eb-8fc0-5e2b547ea723.png)

映射类型支持 alias，并且点击可跳转

**Comment by ls9527** [comment]
正在积极解决， 预计1.4.x修复

**Comment by Nayacco** [comment]
`select * from user where id = #{user.id} and name = #{username}`

希望 sql 参数也能支持代码提示和跳转

**Comment by ls9527** [comment]
1.4.6 已修复

**Comment by Nayacco** [comment]
```java
interface UserMapper : BaseMapper<UserDo> {
    fun insertUser(@Param("username") username: String, @Param("status") status: UserStatus)
}
```

![image](https://user-images.githubusercontent.com/22909744/110270025-e462cb80-7fff-11eb-9b1f-7eb40b99e61a.png)

当点击 xml 中的 username 时无法跳转，点击 xml 中的 status 可以跳转但是跳到了 mapper 的方法名，而不是入参的位置
